/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

/**
 *
 * @author gasp
 */
public class FormMenu extends javax.swing.JFrame {

    private static FormMenu menu = null;
    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        if (Facade.get().logged.getTipo() != TipoBibliotecario.ADMIN) {
            cadastraBibliotecarioButton.setVisible(false);
            removeBibliotecarioButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        companyTitle = new javax.swing.JLabel();
        addMidiaButton = new javax.swing.JButton();
        removeMidiaButton = new javax.swing.JButton();
        emprestimoButton = new javax.swing.JButton();
        devolveButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cadastraClienteButton = new javax.swing.JButton();
        removeBibliotecarioButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        cadastraBibliotecarioButton = new javax.swing.JButton();
        removeClienteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        companyTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        companyTitle.setText("loopTree Biblioteca");

        addMidiaButton.setText("Cadastrar Midia");
        addMidiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMidiaButtonActionPerformed(evt);
            }
        });

        removeMidiaButton.setText("Remover Midia");
        removeMidiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMidiaButtonActionPerformed(evt);
            }
        });

        emprestimoButton.setText("Empréstimo");
        emprestimoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimoButtonActionPerformed(evt);
            }
        });

        devolveButton.setText("Devolução");
        devolveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolveButtonActionPerformed(evt);
            }
        });

        cadastraClienteButton.setText("Cadastrar Cliente");
        cadastraClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraClienteButtonActionPerformed(evt);
            }
        });

        removeBibliotecarioButton.setText("Remover Bibliotecário");
        removeBibliotecarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBibliotecarioButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        cadastraBibliotecarioButton.setText("Cadastrar Bibliotecário");
        cadastraBibliotecarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraBibliotecarioButtonActionPerformed(evt);
            }
        });

        removeClienteButton.setText("Remover Cliente");
        removeClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeClienteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(companyTitle)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addMidiaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeMidiaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emprestimoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(devolveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cadastraClienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeBibliotecarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cadastraBibliotecarioButton)
                                .addComponent(removeClienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addGap(93, 93, 93))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(companyTitle)
                .addGap(18, 18, 18)
                .addComponent(addMidiaButton)
                .addGap(18, 18, 18)
                .addComponent(removeMidiaButton)
                .addGap(18, 18, 18)
                .addComponent(emprestimoButton)
                .addGap(18, 18, 18)
                .addComponent(devolveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastraClienteButton)
                .addGap(18, 18, 18)
                .addComponent(removeClienteButton)
                .addGap(18, 18, 18)
                .addComponent(cadastraBibliotecarioButton)
                .addGap(18, 18, 18)
                .addComponent(removeBibliotecarioButton)
                .addGap(27, 27, 27)
                .addComponent(logoutButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMidiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMidiaButtonActionPerformed
        FormCadastrarMidia formMidia = new FormCadastrarMidia();
        formMidia.setVisible(true);
        this.hide();
    }//GEN-LAST:event_addMidiaButtonActionPerformed

    private void removeMidiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMidiaButtonActionPerformed
       FormRemoverMidia formRemoverMidia = new FormRemoverMidia();
       formRemoverMidia.setVisible(true);
       this.hide();
    }//GEN-LAST:event_removeMidiaButtonActionPerformed

    private void emprestimoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimoButtonActionPerformed
       FormEmprestimo formEmprestimo = new FormEmprestimo();
       formEmprestimo.setVisible(true);
       this.hide();
    }//GEN-LAST:event_emprestimoButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.hide();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void cadastraClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraClienteButtonActionPerformed
        FormCadastraCliente formCliente = new FormCadastraCliente();
        formCliente.setVisible(true);
        this.hide();
    }//GEN-LAST:event_cadastraClienteButtonActionPerformed

    private void removeClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeClienteButtonActionPerformed
        FormRemoverCliente formCliente = new FormRemoverCliente();
        formCliente.setVisible(true);
        this.hide();
    }//GEN-LAST:event_removeClienteButtonActionPerformed

    private void cadastraBibliotecarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraBibliotecarioButtonActionPerformed
        FormCadastraBibliotecario formBibliotecario = new FormCadastraBibliotecario();
        formBibliotecario.setVisible(true);
        this.hide();
    }//GEN-LAST:event_cadastraBibliotecarioButtonActionPerformed

    private void devolveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolveButtonActionPerformed
        FormDevolucao formDevolucao = new FormDevolucao();
        formDevolucao.setVisible(true);
        this.hide();
    }//GEN-LAST:event_devolveButtonActionPerformed

    private void removeBibliotecarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBibliotecarioButtonActionPerformed
        // TODO add your handling code here:
        FormRemoverBibliotecario formRemoverBibliotecario = new FormRemoverBibliotecario();
        formRemoverBibliotecario.setVisible(true);
        this.hide();
    }//GEN-LAST:event_removeBibliotecarioButtonActionPerformed

    public static void showForm(){
        if (menu == null)
            menu = new FormMenu();
        menu.setVisible(true);
    }
    
    public static void hideForm(){
        if( menu != null )
        menu.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormMenu.showForm();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMidiaButton;
    private javax.swing.JButton cadastraBibliotecarioButton;
    private javax.swing.JButton cadastraClienteButton;
    private javax.swing.JLabel companyTitle;
    private javax.swing.JButton devolveButton;
    private javax.swing.JButton emprestimoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton removeBibliotecarioButton;
    private javax.swing.JButton removeClienteButton;
    private javax.swing.JButton removeMidiaButton;
    // End of variables declaration//GEN-END:variables
}
